#!/bin/bash
############################################################
#
# Copyright (C) 2020, Satoshi Konno 
#
# Use of this source code is governed by an MIT-style
# license that can be found in the LICENSE file.
#
############################################################

fddev=/dev/fd0
fdprms="hd ssize=256 head=2 sect=26 cyl=80"

until setfdprm ${fddev} ${fdprms}
do
    echo "Waiting setfdprm ${fddev} ...."
    sleep 1
done

until getfdprm ${fddev}
do
    echo "Waiting getfdprm ${fddev} ...."
    setfdprm ${fddev} ${fdprms}
    sleep 1
done

ddrescue $@
